/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package is.hi.verkefni1;

/**
 *
 * @author jgh06
 */
public class Verkefni1 extends javax.swing.JFrame {

    /**
     * Creates new form Verkefni1
     */
    public Verkefni1() {
        initComponents();
        y = (int)(Math.random()*100) + 1;
        cnt = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        giskText = new javax.swing.JTextField();
        lokagiskText = new javax.swing.JTextField();
        lessThanButton = new javax.swing.JButton();
        commitGisk = new javax.swing.JButton();
        FjoldiTilraunaLabel = new javax.swing.JLabel();
        numOfTriesLabel = new javax.swing.JLabel();
        showYLabel = new javax.swing.JLabel();
        resultLabel = new javax.swing.JLabel();
        showLessThanLabel = new javax.swing.JLabel();
        headingLabel = new javax.swing.JLabel();
        infoLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        giskText.setText("Prófa tölu x");
        giskText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giskTextActionPerformed(evt);
            }
        });

        lokagiskText.setText("Ágiskun á tölu");
        lokagiskText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lokagiskTextActionPerformed(evt);
            }
        });

        lessThanButton.setText("Er x < y ?");
        lessThanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessThanButtonActionPerformed(evt);
            }
        });

        commitGisk.setText("Staðfesta ágiskun");
        commitGisk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                commitGiskActionPerformed(evt);
            }
        });

        FjoldiTilraunaLabel.setText("Fjöldi notaðra spurninga:");

        numOfTriesLabel.setText("0");

        headingLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        headingLabel.setText("Finndu heiltölu y, 1 ≤ y  ≤ 100");

        infoLabel.setText("Þú mátt spyrja tölvuna 8 sinnum hvort x < y.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(FjoldiTilraunaLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                                        .addComponent(lokagiskText))
                                    .addComponent(giskText, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(headingLabel)
                                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lessThanButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(commitGisk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(showLessThanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                            .addComponent(numOfTriesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(showYLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(headingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giskText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lessThanButton)
                    .addComponent(showLessThanLabel))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lokagiskText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(commitGisk))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FjoldiTilraunaLabel)
                    .addComponent(numOfTriesLabel))
                .addGap(18, 18, 18)
                .addComponent(showYLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void giskTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giskTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giskTextActionPerformed

    private void lessThanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessThanButtonActionPerformed
        // TODO add your handling code here:
        try{
            int x = Integer.parseInt(giskText.getText());
            if(x<y){
                showLessThanLabel.setText("x < y");
            }
            else{
                showLessThanLabel.setText("x >= y");
            }
            cnt++;
            if(cnt >= 8){
                lessThanButton.setEnabled(false);
                giskText.setEnabled(false);
            }
            numOfTriesLabel.setText(Integer.toString(cnt));
        }
        catch(Exception e){
        }
    }//GEN-LAST:event_lessThanButtonActionPerformed

    private void commitGiskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_commitGiskActionPerformed
        // TODO add your handling code here:
        try{
            int x = Integer.parseInt(lokagiskText.getText());
            if(x == y){
                resultLabel.setText("Rétt!😀😀");
            }
            else{
                resultLabel.setText("Rangt!😂😂");
            }
            showYLabel.setText("Talan var " + y);
            disableGame();
        }
        catch(Exception e){
            
        }
    }//GEN-LAST:event_commitGiskActionPerformed

    private void lokagiskTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lokagiskTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lokagiskTextActionPerformed
    
    private void disableGame(){
        lokagiskText.setEnabled(false);
        lessThanButton.setEnabled(false);
        giskText.setEnabled(false);
        commitGisk.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Verkefni1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Verkefni1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Verkefni1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Verkefni1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Verkefni1().setVisible(true);
        });
    }
    private int cnt;
    private int y;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FjoldiTilraunaLabel;
    private javax.swing.JButton commitGisk;
    private javax.swing.JTextField giskText;
    private javax.swing.JLabel headingLabel;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton lessThanButton;
    private javax.swing.JTextField lokagiskText;
    private javax.swing.JLabel numOfTriesLabel;
    private javax.swing.JLabel resultLabel;
    private javax.swing.JLabel showLessThanLabel;
    private javax.swing.JLabel showYLabel;
    // End of variables declaration//GEN-END:variables
}
